const express = require("express")
const router = express.Router()

const productData = [
    {
    _id:1,
    title:"Matcha Coffee",
    isNew: true,
    oldPrice: "70",
    price: 55,
    description:"Ceremonial-grade matcha infused with an all-star line up of organic superfoods including our proprietary Six-Mushroom blend, Blue Spirulina, Coconut Milk and more to help you feel and heal like never before.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1689526970-fffa6bce658eb14b6620702e144dd61f?w=600",
    rating: 4.8,
 },
 {
    _id:2,
    title:"Mushroom Coffee",
    isNew: true,
    oldPrice: "50",
    price: 40,
    description:"This is the caffeine-free coffee replacement of your dream. It is naturally packed with prebiotic fibers and it boost metabolism, healthy digestion, regulates sugar level and reduced inflammation.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1689526776-4249104dfa2c7d10181509fdcbe80232?w=600",
    rating: 4.5,
 },
 {
    _id:3,
    title:"Functional Coconut Creamer",
    isNew: true,
    oldPrice: "45",
    price: 35,
    description:" This is a Deliciously creamy taste Coconut Creamer that boosts energy level and open up the brains.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1689526893-7df7458549b3f6b578acdd6dea0bc110?w=600",
    rating: 4,
 },
 {
    _id:4,
    title:"Everlasting Plus",
    isNew: true,
    oldPrice: "60",
    price: 50,
    description:"Evalasting plus is the secret to to lasting longer in bed. If you want to satisfy your woman and give her premium enjoyment then this product is for you. It comes in 2 variants, powdered herbs and teabags.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688982040-e605adc26e72ca69464c96070a3617a8?w=600",
    rating: 4,
 },
 {
    _id:5,
    title:"Sugar Flusher Plus",
    isNew: false,
    oldPrice: "50",
    price: 40,
    description:"This product flushes excess sugar from your body system, cures back pain, cures pile and improves sexuality, it comes in 2 variants, powdered herbs and teabags.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688982090-d7440ce8bc79cdbbc0f3ef876acca9bf?w=600",
    rating: 4,
 },
 {
    _id:6,
    title:"Stallion Plus",
    isNew: false,
    oldPrice: "50",
    price: 40,
    description:"Stallion plus is the energy booster for champions. If you are always tired or exhausted during intercourse, then stallion plus is the solution you need. It also comes in 2 variants, powdered herbs and teabags.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688984421-e3e6bff34b80c8bba4da118e06eacbaa?w=600",
    rating: 4,
 },
 {
    _id:7,
    title:"Hardrock Plus",
    isNew: false,
    oldPrice: "370",
    price: 310,
    description:"It is an erectile dysfunction cure. Hardrock plus is the solution for people struggling with weak erection. This product helps boost blood flow and improves erection. It comes in 2 variants, powdered herbs and teabags.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688984511-21ecf5781b447ac02302d42f7404b6af?w=600",
    rating: 4,
 },
 {
    _id:8,
    title:"Prostrate Solution",
    isNew: true,
    oldPrice: "60",
    price: 50,
    description:"This is the perfect solution to combat prostrate enlargement.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688984600-a3877b931566248c82fdc5227f9acf13?w=600",
    rating: 4,
 },
 {
    _id:9,
    title:"Masturbator Tea",
    isNew: true,
    oldPrice: "60",
    price: 50,
    description:"This product Revitalize your testosterone and return your vigor loss to chronic masturbation and excessive sex.",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688984651-4f4746c4061309c224edfc54c229d434?w=600",
    rating: 4,
 },
 {
    _id:10,
    title:"Immunosin Herbal Capsule",
    isNew: true,
    oldPrice: "55",
    price: 45,
    description:"his Malaty Immunosin herbal capsule is an excellent Immune system booster and blood purifier",
    category: "wellness",
    image: "https://sandbox-uploads.imgix.net/u/1688984706-8a4e089a2686caa80fb219a9872e604e?w=600",
    rating: 4,
 }
]

router.get("/products",(req,res)=>{
    res.send(productData)
})


module.exports = router